---
- name: Ensure magnum client is installed
  pip:
    name: python-magnumclient
    state: present
    virtualenv: "{{ os_container_clusters_venv or omit }}"
  become: "{{ os_container_clusters_venv == None }}"

- name: Ensure container cluster templates exist
  openstack.cloud.coe_cluster_template:
    auth: "{{ os_container_clusters_auth }}"
    auth_type: "{{ os_container_clusters_auth_type }}"
    labels: "{{ item.labels }}"
    external_network_id: "{{ item.external_network_id }}"
    master_flavor_id: "{{ item.master_flavor }}"
    flavor_id: "{{ item.flavor}}"
    image_id: "{{ item.image }}"
    name: "{{ item.name }}"
    coe: "{{ item.coe }}"
    network_driver: "{{ item.network_driver }}"
    is_master_lb_enabled: "{{ item.master_lb_enabled }}"
    is_floating_ip_enabled: "{{ item.floating_ip_enabled }}"
    dns_nameserver: "{{ item.dns_nameserver }}"
    is_public: "{{ item.public }}"
  with_items: "{{ os_container_clusters_templates }}"

