---
- name: Ensure magnum client is installed
  pip:
    name: python-magnumclient
    state: present
    virtualenv: "{{ os_container_clusters_venv or omit }}"
  become: "{{ os_container_clusters_venv == None }}"

- name: Ensure container cluster templates exist
  openstack.cloud.coe_cluster_template:
    auth: "{{ os_container_clusters_auth }}"
    auth_type: "{{ os_container_clusters_auth_type }}"
    labels: "{{ item.labels | default(omit) }}"
    external_network_id: "{{ item.external_network_id | default('external') }}"
    master_flavor_id: "{{ item.master_flavor | default('m1.small') }}"
    flavor_id: "{{ item.flavor | default('m1.small') }}"
    image_id: "{{ item.image | default(undef(hint = 'You must provide an image')) }}}}"
    name: "{{ item.name | default(undef(hint = 'You must provide a name')) }}}}"
    coe: "{{ item.coe | default(undef(hint = 'You must provide a coe')) }}"
    network_driver: "{{ item.network_driver | default(omit) }}"
    is_master_lb_enabled: "{{ item.master_lb_enabled | default(omit) }}"
    is_floating_ip_enabled: "{{ item.floating_ip_enabled | default(omit) }}"
    dns_nameserver: "{{ item.dns_nameserver | default(omit) }}"
    is_public: "{{ item.public | default(omit) }}"
  with_items: "{{ os_container_clusters_templates }}"

