---
- name: Ensure magnum client is installed
  pip:
    name: python-magnumclient
    state: present
    virtualenv: "{{ os_container_clusters_venv or omit }}"
  become: "{{ os_container_clusters_venv == None }}"

- name: Set a fact about the Ansible python interpreter
  set_fact:
    old_ansible_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python' + ansible_python.version.major | string) }}"

- name: Ensure container cluster templates exist
  vars:
    ansible_python_interpreter: "{{ os_container_clusters_venv ~ '/bin/python' if os_container_clusters_venv != None else old_ansible_python_interpreter }}"
  openstack.cloud.coe_cluster_template:
    auth: "{{ os_container_clusters_auth }}"
    auth_type: "{{ os_container_clusters_auth_type }}"
    cacert: "{{ os_container_clusters_cacert | default(omit) }}"
    interface: "{{ os_container_clusters_interface | default(omit, true) }}"
    labels: "{{ item.labels | default(omit) }}"
    external_network_id: "{{ item.external_network_id | default(undef(hint = 'You must provide an external network'))}}"
    master_flavor_id: "{{ item.master_flavor | default(undef(hint = 'You must provide a master flavor'))}}"
    flavor_id: "{{ item.flavor | default(undef(hint = 'You must provide a flavor')) }}"
    image_id: "{{ item.image | default(undef(hint = 'You must provide an image')) }}"
    name: "{{ item.name | default(undef(hint = 'You must provide a name')) }}"
    coe: "{{ item.coe | default(undef(hint = 'You must provide a coe')) }}"
    network_driver: "{{ item.network_driver | default(omit) }}"
    master_lb_enabled: "{{ item.master_lb_enabled | default(omit) }}"
    floating_ip_enabled: "{{ item.floating_ip_enabled | default(omit) }}"
    dns_nameserver: "{{ item.dns_nameserver | default(omit) }}"
    public: "{{ item.public | default(omit) }}"
  with_items: "{{ os_container_clusters_templates }}"

